MyBlog_SD3892/MyBlog_SD3892/Controllers/AdminContentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyBlog_SD3892.Models;
using MyBlog_SD3892.Models.Requests;

namespace MyBlog_SD3892.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class AdminContentController : Controller
    {
        private readonly BlogContext _context;
        public AdminContentController(BlogContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Posts()
        {
            List<CategoryModel> model = new List<CategoryModel>();
            model.Add(new CategoryModel() { Id = 0, cateName = "All" });
            model.AddRange(await _context.Categories.AsNoTracking().ToListAsync());
            ViewData["message"] = TempData["message"];
            return View(model);
        }

        public async Task<IActionResult> Category()
        {
            List<CategoryModel> model = new List<CategoryModel>();
            model.Add(new CategoryModel() { Id = 0, cateName = "All" });
            model.AddRange(await _context.Categories.AsNoTracking().ToListAsync());
            ViewData["message"] = TempData["message"];
            return View(model);
        }

        public async Task<IActionResult> getAllSubCategory(string cateId)
        {
            List<SubCategoryModel> model = new List<SubCategoryModel>();
            model.Add(new SubCategoryModel() { Id = 0, subCateName = "All" });
            model.AddRange(await _context.SubCategories.Where(x => x.categoryId == int.Parse(cateId)).ToListAsync());
            return Json(model);
        }
        [HttpPost]
        public BaseRespose getAllSubCategoryForUpdatePost(string cateId)
        {
            List<SubCategoryModel> model = _context.SubCategories.Where(x => x.categoryId == int.Parse(cateId)).ToList();
            return new BaseRespose() { errorCode = 0, data = model };
        }

        [HttpPost]
        public async Task<IActionResult> addNewCategory([FromForm] CategoryRequest cate)
        {
            if (string.IsNullOrEmpty(cate.cateName))
            {
                TempData["message"] = "Create error";
            }
            else
            {
                _context.Add(new CategoryModel() { cateName = cate.cateName });
                await _context.SaveChangesAsync();
                TempData["message"] = "Create successful";
            }
            return RedirectToAction("Category","AdminContent");
        }

        [HttpPost]
        public async Task<IActionResult> deleteCategory([FromForm] CategoryRequest cate)
        {
            if (string.IsNullOrEmpty(cate.cateId.ToString()))
            {
                TempData["message"] = "Category not found";
            }
            else
            {
                CategoryModel model = _context.Categories.Where(x => x.Id == cate.cateId).Include(x => x.subCategories).FirstOrDefault();
                if (model != null && model.subCategories.Count > 0)
                {
                    TempData["message"] = "Cannot delete this category";
                }
                else
                {
                    _context.Categories.Remove(model);
                    await _context.SaveChangesAsync();
                    TempData["message"] = "Delete successful";
                }
            }
            return RedirectToAction("Category", "AdminContent");
        }

        [HttpPost]
        public async Task<IActionResult> deleteSubCategory([FromForm] SubCategoryRequest subCate)
        {
            if (string.IsNullOrEmpty(subCate.subCateId.ToString()))
            {
                TempData["message"] = "Sub-Category not found";
            }
            else
            {
                SubCategoryModel model = _context.SubCategories.Where(x => x.Id == subCate.subCateId).Include(x => x.posts).FirstOrDefault();
                if (model != null && model.posts.Count > 0)
                {
                    TempData["message"] = "Cannot delete SubCategory";
                }
                else
                {
                    string pathImage = "wwwroot\\images";
                    string oldImageName = pathImage + Path.Combine(model.pathThumbnail);
                    //remove old file
                    if (model.pathThumbnail != "")
                    {
                        if (System.IO.File.Exists(oldImageName))
                        {
                            System.IO.File.Delete(oldImageName);
                        }
                    }
                    _context.SubCategories.Remove(model);
                    await _context.SaveChangesAsync();
                    TempData["message"] = "Delete successful";
                }
            }
            return RedirectToAction("Category", "AdminContent");
        }

        [HttpPost]
        public async Task<IActionResult> updateCategory([FromForm] CategoryRequest cate)
        {
            if (string.IsNullOrEmpty(cate.cateId.ToString()))
            {
                TempData["message"] = "Update error";
            }
            else
            {
                CategoryModel model = _context.Categories.Find(cate.cateId);
                if (model != null)
                {
                    model.cateName = cate.cateName;
                    _context.Categories.Update(model);
                    await _context.SaveChangesAsync();
                    TempData["message"] = "Update successful";
                }
                else
                {
                    TempData["message"] = "Category not found";
                }
            }
            return RedirectToAction("Category", "AdminContent");
        }

        [HttpPost]
        public async Task<IActionResult> addNewSubCategory([FromForm] SubCategoryRequest subCate)
        {
            if (string.IsNullOrEmpty(subCate.subCateName))
            {
                TempData["message"] = "Create error";
            }
            else
            {
                if (subCate.thumbnailSubCate != null)
                {
                    SubCategoryModel model = new SubCategoryModel();
                    model.subCateName = subCate.subCateName;
                    model.categoryId = subCate.cateId;
                    string pathImage = "wwwroot\\images";
                    var uploadFilesPath = Path.Combine(pathImage, "subcategory");

                    if (!Directory.Exists(uploadFilesPath))
                    {
                        Directory.CreateDirectory(uploadFilesPath);
                    }

                    string newFileName = DateTime.Now.ToString("ddMMyyyyhhssmm") + "_" + subCate.thumbnailSubCate.FileName;

                    //get new path
                    string path = pathImage + "\\subcategory\\" + newFileName;

                    //save new file
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        subCate.thumbnailSubCate.CopyTo(stream);
                        model.pathThumbnail = "/subcategory/" + newFileName;
                    }
                    _context.Add(model);
                    await _context.SaveChangesAsync();
                }
                TempData["message"] = "Create successful";
            }
            return RedirectToAction("Category", "AdminContent");
        }

        [HttpPost]
        public async Task<IActionResult> updateSubCategory([FromForm] SubCategoryRequest subCate)
        {
            if (string.IsNullOrEmpty(subCate.subCateId.ToString()))
            {
                TempData["message"] = "Update error";
            }
            else
            {
                SubCategoryModel model = _context.SubCategories.Find(subCate.subCateId);
                if (model != null)
                {
                    model.categoryId = subCate.cateId;
                    model.subCateName = subCate.subCateName;
                    if (subCate.thumbnailSubCate != null)
                    {
                        string pathImage = "wwwroot\\images";
                        var uploadFilesPath = Path.Combine(pathImage, "subcategory");

                        if (!Directory.Exists(uploadFilesPath))
                        {
                            Directory.CreateDirectory(uploadFilesPath);
                        }
                        //get old path
                        string oldImageName = pathImage + Path.Combine(model.pathThumbnail);

                        string newFileName = DateTime.Now.ToString("ddMMyyyyhhssmm") + "_" + subCate.thumbnailSubCate.FileName;

                        //lấy đường dẫn file mới
                        string path = pathImage + "\\subcategory\\" + newFileName;

                        //xóa file cũ
                        if (model.pathThumbnail != "")
                        {
                            if (System.IO.File.Exists(oldImageName))
                            {
                                System.IO.File.Delete(oldImageName);
                            }
                        }

                        //lưu file mới
                        using (var stream = new FileStream(path, FileMode.Create))
                        {
                            subCate.thumbnailSubCate.CopyTo(stream);
                            model.pathThumbnail = "/subcategory/" + newFileName;
                        }
                    }
                    _context.SubCategories.Update(model);
                    await _context.SaveChangesAsync();
                    TempData["message"] = "Create successful";
                }
                else
                {

MyBlog_SD3892/MyBlog_SD3892/Controllers/AdminDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyBlog_SD3892.Models;

namespace MyBlog_SD3892.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class AdminDashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MyBlog_SD3892/MyBlog_SD3892/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyBlog_SD3892.Models;

namespace MyBlog_SD3892.Controllers
{
    public class CategoryController : Controller
    {
        private readonly BlogContext _context;
        public CategoryController(BlogContext context)
        {
            _context = context;
        }
        public IActionResult Index(string cateId)
        {
            if(string.IsNullOrEmpty(cateId))
            {
                return RedirectToAction("Index", "Home");
            }
            CategoryModel model = _context.Categories.Where(x => x.Id == int.Parse(cateId)).Include(x => x.subCategories)
                .ThenInclude((SubCategoryModel o) => o.posts).FirstOrDefault();
            if(model != null)
            {
                List<PostModel> lstPost = new List<PostModel>();
                foreach (SubCategoryModel sub in model.subCategories)
                {
                    lstPost.AddRange(sub.posts);
                }

                model.lstPost = _context.Posts.Where(x => x.subCategories.categoryId == int.Parse(cateId)).ToList();
                model.lstPost.OrderByDescending(x => x.dateCreate);
                return View(model);
            }
            return View();
        }

        public IActionResult SubCategory(string subCateId)
        {
            if (string.IsNullOrEmpty(subCateId))
            {
                return RedirectToAction("Index", "Category");
            }
            SubCategoryModel model = _context.SubCategories.Where(x => x.Id == int.Parse(subCateId)).Include(x=>x.posts).FirstOrDefault();
            return View(model);
        }
    }
}

MyBlog_SD3892/MyBlog_SD3892/Views/AdminContent/Category.cshtml
@model List<MyBlog_SD3892.Models.CategoryModel>
@{
    ViewData["Title"] = "Category";
    Layout = "~/Views/Shared/Admin/_layout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Category</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="AdminDashboard">Home</a></li>
                        <li class="breadcrumb-item active">Category</li>
                    </ol>
                </div>
                <div class="text-danger text-center">@ViewData["message"]</div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <!-- general form elements -->
                    <div class="card card-warning">
                        <div class="card-header">
                            <h3 class="card-title">Filter and Create</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <div class="row card-body">
                            <div class="form-group col-md-6">
                                <label>Category</label>
                                <select id="sl_category" class="form-control">
                                    @foreach (CategoryModel category in Model)
                                    {
                                        <option value="@category.Id">@category.cateName</option>
                                    }
                                </select>
                            </div>
                            <div class="form-group col-md-6">
                                <label>Sub-Category</label>
                                <select id="sl_subCategory" class="form-control">
                                </select>
                            </div>
                            <div class="form-group col-md-6">
                                <button class="btn btn-info w-100" id="btnSortCategory">Sort</button>
                            </div>
                            <div class="form-group col-md-6">
                                <button class="btn btn-success w-100" data-toggle="modal" data-target="#modelId" onclick="createCategory()">New</button>
                            </div>
                        </div>
                    </div>
                    <!-- /.card -->
                    <!-- Form Element sizes -->
                    <div class="card card-outline card-info">
                        <div class="card-header">
                            <h3 class="card-title">Sort Result</h3>
                        </div>
                        <div class="card-body px-0">
                            <table id="tbl_categoryResult" class="w-100 table table-hover table-bordered">
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

<!-- Modal -->
<div class="modal fade" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitle"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="formCategory" enctype="multipart/form-data">
                <div class="modal-body" id="modalBody">
                </div>
                <div class="modal-footer" id="modalFooter">
                </div>
            </form>
        </div>
    </div>
</div>

MyBlog_SD3892/MyBlog_SD3892/Views/AdminContent/Comments.cshtml
@{
    ViewData["Title"] = "Comments";
    Layout = "~/Views/Shared/Admin/_layout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>General Form</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">General Form</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <!-- general form elements -->
                    <div class="card card-warning">
                        <div class="card-header">
                            <h3 class="card-title">Quick Example</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <div class="row card-body">
                            <div class="form-group col-md-6">
                                <label>Category</label>
                                <select class="form-control">
                                    <option>option 1</option>
                                    <option>option 2</option>
                                    <option>option 3</option>
                                    <option>option 4</option>
                                    <option>option 5</option>
                                </select>
                            </div>
                            <div class="form-group col-md-6">
                                <label>Category</label>
                                <select class="form-control">
                                    <option>option 1</option>
                                    <option>option 2</option>
                                    <option>option 3</option>
                                    <option>option 4</option>
                                    <option>option 5</option>
                                </select>
                            </div>
                            <div class="form-group col-12 row no-gutters">
                                <label for="inputEmail3" class="col-sm-1 col-form-label">Email</label>
                                <div class="col-sm-11">
                                    <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
                                </div>
                            </div>
                            <div class="col-12">
                                <button class="btn btn-info w-100 h-100">Sort</button>
                            </div>
                        </div>
                    </div>
                    <!-- /.card -->
                    <!-- Form Element sizes -->
                    <div class="card card-outline card-info">
                        <div class="card-header">
                            <h3 class="card-title">Different Height</h3>
                        </div>
                        <div class="card-body px-0">
                            <table class="w-100 table table-hover table-bordered">
                                <thead class="text-center">
                                    <tr>
                                        <th>sdfsdf</th>
                                        <th>sdfsdf</th>
                                        <th>sfsdf</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td class="text-center">
                                            <button class="btn btn-outline-danger" data-toggle="modal" data-target="#modelId"><i class="fa fa-trash-alt"></i></button>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

<!-- Modal -->
<div class="modal fade" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">smertert</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Xóa
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</div>

MyBlog_SD3892/MyBlog_SD3892/Views/AdminContent/Index.cshtml
@model List<MyBlog_SD3892.Models.CategoryModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/Admin/_layout.cshtml";
}

    <div class="content-wrapper">
            <div class="toast" data-autoHide="false" style="position: absolute; top: 0; right: 0; z-index:999; width:200px">
                <div class="toast-header">
                    <strong class="mr-auto text-danger" id="toastTitle"></strong>
                    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="toast-body" id="toastBody"></div>
            </div>
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Posts</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a asp-action="Posts" asp-controller="AdminContent">Home</a></li>
                            <li class="breadcrumb-item active">Posts</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <!-- general form elements -->
                        <div class="card card-warning">
                            <div class="card-header">
                                <h3 class="card-title">Quick Example</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <div class="row card-body">
                                <div class="form-group col-md-6">
                                    <label>Category</label>
                                    <select id="sl_category" class="form-control">
                                        @foreach (CategoryModel category in Model)
                                        {
                                            <option value="@category.Id">@category.cateName</option>
                                        }
                                    </select>
                                </div>
                                <div class="form-group col-md-6">
                                    <label>Sub-Category</label>
                                    <select id="sl_subCategory" class="form-control">
                                    </select>
                                </div>
                                <div class="col-md-6">
                                    <button class="btn btn-info w-100">Sort</button>
                                </div>
                                <div class="col-md-6">
                                    <button class="btn btn-success w-100" onclick="addNewPost()">New</button>
                                </div>
                            </div>
                        </div>
                        <!-- /.card -->
                        <!-- Form Element sizes -->
                        <div class="card card-outline card-info">
                            <div class="card-header">
                                <h3 class="card-title">Different Height</h3>
                            </div>
                            <div class="card-body px-0">
                                <table class="w-100 table table-hover table-bordered">
                                    <thead class="text-center">
                                        <tr>
                                            <th>sdfsdf</th>
                                            <th>sdfsdf</th>
                                            <th>sfsdf</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td></td>
                                            <td></td>
                                            <td class="text-center">
                                                <button class="btn btn-outline-info"><i class="fa fa-pencil-alt"></i></button>
                                                <button class="btn btn-outline-danger"><i class="fa fa-trash-alt"></i></button>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>

<!-- Modal -->
<div class="modal fade" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog full-modal" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitle"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form enctype="multipart/form-data">
            <div class="modal-body" id="modalBody">
            </div>
            <div class="modal-footer" id="modalFooter">
            </div>
            </form>
        </div>
    </div>
</div>