MyBlog_SD3892/MyBlog_SD3892/Controllers/AdminAuthController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyBlog_SD3892.Models;
using MyBlog_SD3892.Models.Requests;

namespace MyBlog_SD3892.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class AdminAuthController : Controller
    {
        private readonly BlogContext _context;
        public AdminAuthController(BlogContext context)
        {
            _context = context;
        }

        [AllowAnonymous]
        public IActionResult Login()
        {
            ViewData["message"] = TempData["message"];
            return View();
        }

        [AllowAnonymous]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login", "AdminAuth");
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> LoginUser(UserRequest user)
        {
            UserModel model = new UserModel();
            PasswordHasher<UserModel> hash = new PasswordHasher<UserModel>();
            model = _context.Users.Where(x => x.email == user.userEmail).Include(x => x.role).FirstOrDefault();
            if (model != null)
            {

                if (hash.VerifyHashedPassword(model, model.password, user.userPassword) == PasswordVerificationResult.Success)
                {
                    var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                    identity.AddClaim(new Claim(ClaimTypes.Email, model.email));
                    identity.AddClaim(new Claim(ClaimTypes.Role, model.role.roleName));
                    identity.AddClaim(new Claim("Avatar", model.pathAvatar));
                    identity.AddClaim(new Claim("UserId", model.Id.ToString()));
                    identity.AddClaim(new Claim(ClaimTypes.Name, model.fullName));
                    var principal = new ClaimsPrincipal(identity);
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                }
                else
                {
                    TempData["message"] = "Email or password incorrect";
                }
            }
            else
            {
                TempData["message"] = "Email or password incorrect";
            }
            return RedirectToAction("Index", "AdminDashboard");
        }

        [AllowAnonymous]
        public IActionResult ForgotPW()
        {
            return View();
        }

        [AllowAnonymous]
        public IActionResult ChangePW()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Users()
        {
            UserModel models = new UserModel();
            models.lstUser = _context.Users.Include(x => x.role).ToList();
            models.lstRole = _context.Roles.ToList();
            return View(models);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Roles()
        {
            ViewData["message"] = TempData["message"];
            return View(_context.Roles.ToList()); ;
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult addNewRole(string roleName)
        {
            if (string.IsNullOrEmpty(roleName))
            {
                TempData["message"] = "Create error";
                return RedirectToAction("Roles", "AdminAuth");
            }
            _context.Roles.Add(new RoleModel() { roleName = roleName });
            _context.SaveChanges();
            return RedirectToAction("Roles", "AdminAuth");
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult addNewUser([FromForm]UserRequest user)
        {
            if (string.IsNullOrEmpty(user.userEmail))
            {
                TempData["message"] = "Create error";
            }
            else
            {
                if (user.userPathAvatar != null)
                {
                    UserModel model = new UserModel();
                    model.password = new PasswordHasher<UserModel>().HashPassword(model, user.userPassword);
                    model.address = user.userAddress;
                    model.description = user.userDescription;
                    model.email = user.userEmail;
                    model.fullName = user.userFullName;
                    model.phoneNumber = user.userPhone;
                    model.roleId = user.userRoleId;
                    string pathImage = "wwwroot\\images";
                    var uploadFilesPath = Path.Combine(pathImage, "users");

                    if (!Directory.Exists(uploadFilesPath))
                    {
                        Directory.CreateDirectory(uploadFilesPath);
                    }

                    string newFileName = DateTime.Now.ToString("ddMMyyyyhhssmm") + "_" + user.userPathAvatar.FileName;

                    //get new path
                    string path = pathImage + "\\users\\" + newFileName;

                    //save new file
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        user.userPathAvatar.CopyTo(stream);
                        model.pathAvatar = "/users/" + newFileName;
                    }
                    _context.Users.Add(model);
                    _context.SaveChangesAsync();
                }
                TempData["message"] = "Create successful";
            }
            return RedirectToAction("Users", "AdminAuth");
        }

    }
}

MyBlog_SD3892/MyBlog_SD3892/Controllers/AdminDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyBlog_SD3892.Models;

namespace MyBlog_SD3892.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class AdminDashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MyBlog_SD3892/MyBlog_SD3892/Controllers/AdminNotifyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MyBlog_SD3892.Controllers
{
    public class AdminNotifyController : Controller
    {
        public IActionResult Admin()
        {
            return View();
        }

        public IActionResult Message()
        {
            return View();
        }
    }
}

MyBlog_SD3892/MyBlog_SD3892/Views/AdminAuth/ChangePW.cshtml
@{
    ViewData["Title"] = "ChangePW";
    Layout = "~/Views/AdminAuth/_layout.cshtml";
}

    <div class="login-box">
        <div class="login-logo">
            <a href="../../index2.html"><b>Admin</b>LTE</a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">You are only one step a way from your new password, recover your password now.</p>

                <form action="login.html" method="post">
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" placeholder="Your Password">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" placeholder="New Password">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" class="form-control" placeholder="Confirm New Password">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary btn-block">Change password</button>
                        </div>
                        <!-- /.col -->
                    </div>
                </form>

                <p class="mt-3 mb-1">
                    <a asp-action="Login" asp-controller="AdminAuth">Login</a>
                </p>
            </div>
            <!-- /.login-card-body -->
        </div>
    </div>

MyBlog_SD3892/MyBlog_SD3892/Views/AdminAuth/ForgotPW.cshtml
@{
    ViewData["Title"] = "ForgotPW";
    Layout = "~/Views/AdminAuth/_layout.cshtml";
}

    <div class="login-box">
        <div class="login-logo">
            <a href="../../index2.html"><b>Admin</b>LTE</a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">You forgot your password? Here you can easily retrieve a new password.</p>

                <form action="recover-password.html" method="post">
                    <div class="input-group mb-3">
                        <input type="email" class="form-control" placeholder="Email">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary btn-block">Request new password</button>
                        </div>
                        <!-- /.col -->
                    </div>
                </form>
                <p class="mt-3 mb-1">
                    <a asp-action="Login" asp-controller="AdminAuth">Login</a>
                </p>
            </div>
            <!-- /.login-card-body -->
        </div>
    </div>

MyBlog_SD3892/MyBlog_SD3892/Views/AdminAuth/Login.cshtml
@{
    ViewData["Title"] = "Login";
    Layout = "~/Views/AdminAuth/_layout.cshtml";
}

    <div class="login-box">
        <div class="login-logo">
            <a href="../../index2.html"><b>Admin</b>LTE</a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Sign in to start your session</p>

                <form asp-action="LoginUser" asp-controller="AdminAuth" method="post">
                    <div class="input-group mb-3">
                        <input type="email" name="userEmail" class="form-control" placeholder="Email">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <input type="password" name="userPassword" class="form-control" placeholder="Password">
                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
                        </div>
                        <div class="col-12 text-danger text-center">@ViewData["message"]</div>
                        <!-- /.col -->
                    </div>
                </form>

                <p class="mb-1">
                    <a asp-action="ForgotPW" asp-controller="AdminAuth">I forgot my password</a>
                </p>
            </div>
            <!-- /.login-card-body -->
        </div>
    </div>

MyBlog_SD3892/MyBlog_SD3892/Views/AdminAuth/Roles.cshtml
@model List<MyBlog_SD3892.Models.RoleModel>
@{
    ViewData["Title"] = "Users";
    Layout = "~/Views/Shared/Admin/_layout.cshtml";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Roles</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-action="Roles" asp-controller="AdminDashboard">Home</a></li>
                        <li class="breadcrumb-item active">Roles</li>
                    </ol>
                </div>
                <div class="text-danger text-center">@ViewData["message"]</div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <!-- general form elements -->
                    <div class="card card-warning">
                        <div class="card-header">
                            <h3 class="card-title">Create</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <div class="row card-body">
                            <form class="w-100" method="post" asp-action="AddNewRole" asp-controller="AdminAuth">
                                <div class="form-group col-12">
                                    <label>Role name</label>
                                    <input type="text" name="roleName" class="form-control" placeholder="Enter role name" />
                                </div>
                                <div class="form-group col-12">
                                    <button type="submit" class="btn btn-success w-100">New</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <!-- /.card -->
                    <!-- Form Element sizes -->
                    <div class="card card-outline card-info">
                        <div class="card-header">
                            <h3 class="card-title">List roles</h3>
                        </div>
                        <div class="card-body px-0">
                            <table class="w-100 table table-hover table-bordered">
                                <thead class="text-center">
                                    <tr>
                                        <th>ID</th>
                                        <th>Role name</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (RoleModel role in Model)
                                    {
                                        <tr>
                                            <td class="text-center">@role.Id</td>
                                            <td>@role.roleName</td>
                                            <td class="text-center">
                                                <button class="btn btn-outline-info" data-toggle="modal" data-target="#modelId"><i class="fa fa-pencil-alt"></i></button>
                                                <button class="btn btn-outline-danger"><i class="fa fa-trash-alt"></i></button>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>

<!-- Modal -->
<div class="modal fade" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">smertert</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="exampleInputEmail1">Name</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Email</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Phone</label>
                    <input type="tel" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Passord</label>
                    <input type="password" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Address</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
                </div>
                <div class="form-group">
                    <label for="exampleInputFile">Avatar</label>
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="customFile">
                        <label class="custom-file-label" for="customFile">Choose file</label>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</div>

MyBlog_SD3892/MyBlog_SD3892/Views/AdminAuth/_layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <partial name="~/Views/Shared/Admin/_head.cshtml" />
</head>
<body class="hold-transition login-page">
    @RenderBody()
    <!-- /.login-box -->
    <!-- jQuery -->
    <partial name="~/Views/Shared/Admin/_scripts.cshtml" />

</body>
</html>

MyBlog_SD3892/MyBlog_SD3892/Views/AdminAuth/_userDisplay.cshtml
@model MyBlog_SD3892.Models.UserModel
<!-- Sidebar user panel (optional) -->
<div class="user-panel mt-3 pb-3 mb-3 d-flex">
    <div class="image">
        <img src="@Url.Content("~/images" + Model.pathAvatar)" class="img-circle elevation-2 img-admin-avatar" alt="@Model.fullName">
    </div>
    <div class="info">
        <a class="d-block">@Model.fullName | @Model.role.roleName</a>
    </div>
</div>
<!-- Sidebar Menu -->
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
        with font-awesome or any other icon font library -->
        <li class="nav-item">
            <a asp-action="Index" asp-controller="AdminDashboard" class="nav-link">
                <i class="nav-icon fas fa-tachometer-alt"></i>
                <p>
                    Dashboard
                </p>
            </a>
        </li>
        <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
                <i class="nav-icon fas fa-edit"></i>
                <p>
                    Content
                    <i class="fas fa-angle-left right"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a asp-action="Posts" asp-controller="AdminContent" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Posts</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-action="Category" asp-controller="AdminContent" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Category</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-action="Comments" asp-controller="AdminContent" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Comments</p>
                    </a>
                </li>
            </ul>
        </li>
        <li class="nav-item has-treeview">
            <a href="#" class="nav-link active">
                <i class="nav-icon fas fa-chart-pie"></i>
                <p>
                    Statistical
                    <i class="fas fa-angle-left right"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a asp-controller="AdminStatistical" asp-action="Posts" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Posts</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-controller="AdminStatistical" asp-action="Comments" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Comments</p>
                    </a>
                </li>
            </ul>
        </li>
        <li class="nav-item has-treeview">
            <a href="#" class="nav-link active">
                <i class="nav-icon fas fa-comment-dots"></i>
                <p>
                    Notification
                    <i class="fas fa-angle-left right"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a asp-controller="AdminNotify" asp-action="message" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Message</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-controller="AdminNotify" asp-action="admin" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Admin</p>
                    </a>
                </li>
            </ul>
        </li>
        @if (Model.role.roleName == "Admin")
        {
            <li class="nav-item has-treeview">
                <a href="#" class="nav-link active">
                    <i class="nav-icon fa fa-user-clock"></i>
                    <p>
                        Users
                        <i class="fas fa-angle-left right"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a asp-action="Roles" asp-controller="AdminAuth" class="nav-link">
                            <i class="fa fa-users-cog nav-icon"></i>
                            <p>Roles</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-action="Users" asp-controller="AdminAuth" class="nav-link">
                            <i class="fa fa-users nav-icon"></i>
                            <p>Users</p>
                        </a>
                    </li>
                </ul>
            </li>
        }
    </ul>
</nav>
<!-- /.sidebar-menu -->